### ISSUE TITLE
Page Title and Favicon is default

### ISSUE THREAD

**Issue by LarsGKodehode** [Andreastak86/22-portfolio#1]
https://github.com/Andreastak86/22-portfolio/blob/8e268c284b5a631e73ff894394499b4198578fb7/public/index.html#L27

Ser du har fått en ny portfolio opp å gå 😄 

Bet meg litt i merke tittelen og faviconet på siden 😉

**Comment by Andreastak86** [comment]
Heisann. Takk for tips:-D
Ja jeg burde vel gjort noe med titel og favicon;-)
Skal lage meg ny portfolio nå i starten av neste år med nextJS og Tailwind. Tenker den kommer til å bli hakket bedre enn denne her. 
Hvordan går det med din portfolio da?

Sjekk forresten ut siden vi har laget og levert til kunde: www.bergenarmwrestling.no
